PATH ridership information is published as a PDF which makes it so unbelievably inconvenient to work with for analytic purposes.
PATH ridership data: https://www.panynj.gov/path/statistics.html

In [126]:
# tabula requires java
import tabula
import pandas as pd
import numpy as np

In [127]:
#constants
months = [1,2,3,4,5,6,7,8,9,10,11,12]

In [173]:
def get_raw_tables(pdf_path, multiple_tables=True, encoding='ISO-8859-1', pages='all'):
    raw_tables = tabula.read_pdf(
        pdf_path,
        multiple_tables = multiple_tables,
        encoding = encoding,
        pages = pages)
    print("Tables found: {}".format(len(raw_tables)))
    return raw_tables

def filter_raw_tables(raw_tables): 
    # Only tables with 8 rows are valid for our case 
    valid_tables = [s for s in raw_tables if len(s) == 8]
    valid_tables = valid_tables[0:38]
    print("Valid Tables: {}".format(len(valid_tables)))
    return valid_tables

def get_monthly_tables(valid_tables):
    month_tables = []
    monthly_by_section = []

    columns_tots = ['Station','MonthTotal','AvgWeekday', 'AvgSaturday', 'AvgSunday', 'AvgHoliday']
    columns_daily_tots = ['Station','AvgDailyTotal','TotalWeekdayCount','TotalSaturdayCount','TotalSundayCount','TotalHolidayCount']

    #join tables that were split in two horizontally 
    for i in np.arange(len(valid_tables),step=2):
        print(i)
        temp = pd.concat([valid_tables[i],valid_tables[i+1]])
        temp = temp.reset_index(drop=True)
        monthly_by_section.append(temp)
    print("hi ")
    for i in np.arange(len(monthly_by_section),step=2):
        print(i)
        monthly_by_section[i].columns = columns_tots
        monthly_by_section[i+1].columns = columns_daily_tots

        temp = pd.concat([monthly_by_section[i], monthly_by_section[i+1]], axis=1)
        temp = temp.loc[:,~temp.columns.duplicated()]
        temp['Month'] = months[i//2]
        temp['Year'] = year
        
        month_tables.append(temp)

    print("Total Monthly Tables: {}".format(len(month_tables)))
    return month_tables

In [143]:
# years = [2015]
# for year in years:
year = 2015
pdf_path = "../data/path_ridership_data/{}-PATH-Monthly-Ridership-Report.pdf".format(year)
file_name_output = "{}-PATH-Monthly-Ridership-Report.csv".format(year)

print("Data File Path: {}".format(pdf_path))
print("Output File Name: {}".format(file_name_output))

raw_tables = get_raw_tables(pdf_path)

Data File Path: ../data/path_ridership_data/2015-PATH-Monthly-Ridership-Report.pdf
Output File Name: 2015-PATH-Monthly-Ridership-Report.csv
Tables found: 87

In [175]:
print(raw_tables)
# valid_tables = filter_raw_tables(raw_tables)
# print((valid_tables))
# month_tables = get_monthly_tables(valid_tables)

# master_df = pd.concat(month_tables)
# print("Rows in CSV: {}".format(len(master_df)))
# master_df.to_csv(file_name_output, index=False)
# print("Done with year {}".format(year))

[                    0          1        2       3       4       5
0  Christopher Street    105,982    4,078   2,355   1,948   2,424
1           9thStreet    118,812    4,186   3,396   2,892   3,274
2          14thStreet    219,205    8,159   5,456   4,326   5,718
3          23rdStreet    189,374    7,990   2,756   2,183   3,526
4          33rdStreet    816,970   32,345  15,493  12,226  21,846
5     UPTOWN SUBTOTAL  1,450,343   56,758  29,456  23,575  36,788
6                 WTC    974,660   43,725   8,982   6,681  14,260
7   NEW YORK SUBTOTAL  2,425,003  100,483  38,438  30,256  51,048,                     0       1          2        3        4        5
0  Christopher Street   3,419     81,568   11,774    7,793    4,847
1           9thStreet   3,833     83,718   16,979   11,567    6,548
2          14thStreet   7,071    163,189   27,279   17,302   11,435
3          23rdStreet   6,109    159,810   13,779    8,733    7,052
4          33rdStreet  26,354    646,908   77,466   48,904   43,692
5     UPTOWN SUBTOTAL  46,785  1,135,193  147,277   94,299   73,574
6                 WTC  31,441    874,507   44,910   26,723   28,520
7   NEW YORK SUBTOTAL  78,226  2,009,700  192,187  121,022  102,094,                      0       1          2        3        4        5
0               Newark  18,830    503,809   39,251   22,236   18,433
1             Harrison   4,937    132,075   10,259    5,522    5,182
2       Journal Square  18,968    468,263   59,324   35,314   25,105
3         Grove Street  12,662    318,741   37,933   21,203   14,639
4       Exchange Place   9,918    280,313   12,875    7,005    7,268
5     Pavonia/ Newport  13,058    331,498   35,969   21,362   15,968
6              Hoboken  19,771    506,856   56,571   29,212   20,272
7  NEW JERSEY SUBTOTAL  98,144  2,541,555  252,182  141,854  106,867,                         0          1        2         3        4        5
0   PATH Ridership Report        NaN      NaN       NaN      NaN      NaN
1            January 2015        NaN      NaN       NaN      NaN      NaN
2                     NaN    January  Average   Average  Average  Average
3                     NaN       2015  Weekday  Saturday   Sunday  Holiday
4                     NaN     Totals      NaN       NaN      NaN      NaN
5       NEW YORK STATIONS        NaN       20         5        4        2
6      Christopher Street    105,982    4,078     2,355    1,948    2,424
7               9thStreet    118,812    4,186     3,396    2,892    3,274
8              14thStreet    219,205    8,159     5,456    4,326    5,718
9              23rdStreet    189,374    7,990     2,756    2,183    3,526
10             33rdStreet    816,970   32,345    15,493   12,226   21,846
11        UPTOWN SUBTOTAL  1,450,343   56,758    29,456   23,575   36,788
12                    WTC    974,660   43,725     8,982    6,681   14,260
13      NEW YORK SUBTOTAL  2,425,003  100,483    38,438   30,256   51,048
14    NEW JERSEY STATIONS        NaN      NaN       NaN      NaN      NaN
15                 Newark    583,729   25,190     7,850    5,559    9,216
16               Harrison    153,038    6,604     2,052    1,380    2,591
17         Journal Square    588,006   23,413    11,865    8,828   12,552
18           Grove Street    392,516   15,937     7,587    5,301    7,320
19         Exchange Place    307,461   14,016     2,575    1,751    3,634
20       Pavonia/ Newport    404,797   16,575     7,194    5,340    7,984
21                Hoboken    612,911   25,343    11,314    7,303   10,136
22    NEW JERSEY SUBTOTAL  3,042,458  127,078    50,437   35,462   53,433
23          MONTHLY TOTAL  5,467,461  227,563    88,874   65,719  104,480,                     0          1        2       3       4       5
0  Christopher Street    101,447    4,286   2,544   1,984   1,897
1           9thStreet    122,692    4,920   3,695   3,002   2,429
2          14thStreet    209,969    8,735   5,504   4,342   4,629
3          23rdStreet    192,040    8,780   3,068   2,428   3,240
4          33rdStreet    777,547   34,090  15,911  12,574  15,890
5     UPTOWN SUBTOTAL  1,403,695   60,811  30,722  24,330  28,085
6                 WTC    971,537   46,888   9,685   7,392  12,353
7   NEW YORK SUBTOTAL  2,375,232  107,699  40,407  31,722  40,438,                     0       1          2        3        4       5
0  Christopher Street   3,623     81,439   10,176    7,935   1,897
1           9thStreet   4,382     93,478   14,779   12,006   2,429
2          14thStreet   7,499    165,956   22,017   17,367   4,629
3          23rdStreet   6,859    166,818   12,271    9,711   3,240
4          33rdStreet  27,770    647,719   63,644   50,294  15,890
5     UPTOWN SUBTOTAL  50,132  1,155,410  122,887   97,313  28,085
6                 WTC  34,698    890,873   38,741   29,570  12,353
7   NEW YORK SUBTOTAL  84,830  2,046,283  161,628  126,883  40,438,                      0        1          2        3        4       5
0               Newark   20,778    513,873   33,839   23,767  10,318
1             Harrison    5,340    132,120    8,921    5,886   2,582
2       Journal Square   20,886    483,849   51,679   37,076  12,204
3         Grove Street   13,847    325,497   32,324   22,276   7,613
4       Exchange Place   11,294    292,901   11,355    8,027   3,936
5     Pavonia/ Newport   14,682    347,388   33,061   23,129   7,523
6              Hoboken   21,565    517,360   46,098   30,680   9,690
7  NEW JERSEY SUBTOTAL  108,392  2,612,988  217,277  150,841  53,866,                         0          1        2         3        4        5
0   PATH Ridership Report        NaN      NaN       NaN      NaN      NaN
1           February 2015        NaN      NaN       NaN      NaN      NaN
2                     NaN   February  Average   Average  Average  Average
3                     NaN       2015  Weekday  Saturday   Sunday  Holiday
4                     NaN     Totals      NaN       NaN      NaN      NaN
5       NEW YORK STATIONS        NaN       19         4        4        1
6      Christopher Street    101,447    4,286     2,544    1,984    1,897
7               9thStreet    122,692    4,920     3,695    3,002    2,429
8              14thStreet    209,969    8,735     5,504    4,342    4,629
9              23rdStreet    192,040    8,780     3,068    2,428    3,240
10             33rdStreet    777,547   34,090    15,911   12,574   15,890
11        UPTOWN SUBTOTAL  1,403,695   60,811    30,722   24,330   28,085
12                    WTC    971,537   46,888     9,685    7,392   12,353
13      NEW YORK SUBTOTAL  2,375,232  107,699    40,407   31,722   40,438
14    NEW JERSEY STATIONS        NaN      NaN       NaN      NaN      NaN
15                 Newark    581,797   27,046     8,460    5,942   10,318
16               Harrison    149,509    6,954     2,230    1,472    2,582
17         Journal Square    584,808   25,466    12,920    9,269   12,204
18           Grove Street    387,710   17,131     8,081    5,569    7,613
19         Exchange Place    316,219   15,416     2,839    2,007    3,936
20       Pavonia/ Newport    411,101   18,284     8,265    5,782    7,523
21                Hoboken    603,828   27,229    11,524    7,670    9,690
22    NEW JERSEY SUBTOTAL  3,034,972  137,526    54,319   37,711   53,866
23          MONTHLY TOTAL  5,410,204  245,225    94,726   69,431   94,304,                     0          1        2       3       4  5
0  Christopher Street    120,196    4,432   2,720   2,362  0
1           9thStreet    141,731    4,955   3,960   3,375  0
2          14thStreet    244,941    8,845   6,303   5,029  0
3          23rdStreet    221,525    8,881   3,368   2,535  0
4          33rdStreet    920,609   35,350  18,096  14,106  0
5     UPTOWN SUBTOTAL  1,649,002   62,463  34,447  27,407  0
6                 WTC  1,147,600   47,948  11,545   9,313  0
7   NEW YORK SUBTOTAL  2,796,602  110,411  45,992  36,720  0,                     0       1          2        3        4  5
0  Christopher Street   3,877     97,506   10,882   11,808  0
1           9thStreet   4,572    109,020   15,838   16,873  0
2          14thStreet   7,901    194,583   25,213   25,145  0
3          23rdStreet   7,146    195,378   13,470   12,677  0
4          33rdStreet  29,697    777,697   72,384   70,528  0
5     UPTOWN SUBTOTAL  53,194  1,374,184  137,787  137,031  0
6                 WTC  37,019  1,054,854   46,181   46,565  0
7   NEW YORK SUBTOTAL  90,213  2,429,038  183,968  183,596  0,                      0        1          2        3        4  5
0               Newark   22,118    611,188   38,581   35,895  0
1             Harrison    5,881    160,669   10,695   10,960  0
2       Journal Square   21,950    571,376   57,095   51,976  0
3         Grove Street   14,547    383,855   36,035   31,076  0
4       Exchange Place   12,016    346,766   13,316   12,424  0
5     Pavonia/ Newport   15,381    408,596   35,841   32,384  0
6              Hoboken   22,516    599,256   55,361   43,392  0
7  NEW JERSEY SUBTOTAL  114,411  3,081,706  246,924  218,107  0,                         0          1        2         3        4        5
0   PATH Ridership Report        NaN      NaN       NaN      NaN      NaN
1              March 2015        NaN      NaN       NaN      NaN      NaN
2                     NaN      March  Average   Average  Average  Average
3                     NaN       2015  Weekday  Saturday   Sunday  Holiday
4                     NaN     Totals      NaN       NaN      NaN      NaN
5       NEW YORK STATIONS        NaN       22         4        5        0
6      Christopher Street    120,196    4,432     2,720    2,362        0
7               9thStreet    141,731    4,955     3,960    3,375        0
8              14thStreet    244,941    8,845     6,303    5,029        0
9              23rdStreet    221,525    8,881     3,368    2,535        0
10             33rdStreet    920,609   35,350    18,096   14,106        0
11        UPTOWN SUBTOTAL  1,649,002   62,463    34,447   27,407        0
12                    WTC  1,147,600   47,948    11,545    9,313        0
13      NEW YORK SUBTOTAL  2,796,602  110,411    45,992   36,720        0
14    NEW JERSEY STATIONS        NaN      NaN       NaN      NaN      NaN
15                 Newark    685,664   27,781     9,645    7,179        0
16               Harrison    182,324    7,303     2,674    2,192        0
17         Journal Square    680,447   25,972    14,274   10,395        0
18           Grove Street    450,966   17,448     9,009    6,215        0
19         Exchange Place    372,506   15,762     3,329    2,485        0
20       Pavonia/ Newport    476,821   18,573     8,960    6,477        0
21                Hoboken    698,009   27,239    13,840    8,678        0
22    NEW JERSEY SUBTOTAL  3,546,737  140,078    61,731   43,621        0
23          MONTHLY TOTAL  6,343,339  250,488   107,723   80,341        0,                     0          1        2       3       4  5
0  Christopher Street    128,753    4,752   3,358   2,693  0
1           9thStreet    151,566    5,357   4,672   3,758  0
2          14thStreet    246,791    9,111   6,581   5,006  0
3          23rdStreet    221,746    8,932   3,593   2,719  0
4          33rdStreet    952,786   36,569  20,794  16,272  0
5     UPTOWN SUBTOTAL  1,701,642   64,721  38,998  30,448  0
6                 WTC  1,182,685   49,166  14,224  11,036  0
7   NEW YORK SUBTOTAL  2,884,327  113,887  53,222  41,484  0,                     0       1          2        3        4  5
0  Christopher Street   4,292    104,551   13,430   10,772  0
1           9thStreet   5,052    117,845   18,687   15,034  0
2          14thStreet   8,226    200,444   26,325   20,022  0
3          23rdStreet   7,392    196,497   14,373   10,876  0
4          33rdStreet  31,760    804,518   83,178   65,090  0
5     UPTOWN SUBTOTAL  56,721  1,423,855  155,993  121,794  0
6                 WTC  39,423  1,081,645   56,897   44,143  0
7   NEW YORK SUBTOTAL  96,144  2,505,500  212,890  165,937  0,                      0        1          2        3        4  5
0               Newark   23,581    631,014   44,536   31,893  0
1             Harrison    6,464    170,983   12,586   10,344  0
2       Journal Square   23,405    590,458   64,914   46,768  0
3         Grove Street   15,478    395,964   40,871   27,509  0
4       Exchange Place   12,628    351,754   15,891   11,198  0
5     Pavonia/ Newport   16,432    421,723   42,457   28,777  0
6              Hoboken   23,674    616,395   56,690   37,148  0
7  NEW JERSEY SUBTOTAL  121,662  3,178,291  277,945  193,637  0,                         0          1        2         3        4        5
0   PATH Ridership Report        NaN      NaN       NaN      NaN      NaN
1              April 2015        NaN      NaN       NaN      NaN      NaN
2                     NaN      April  Average   Average  Average  Average
3                     NaN       2015  Weekday  Saturday   Sunday  Holiday
4                     NaN     Totals      NaN       NaN      NaN      NaN
5       NEW YORK STATIONS        NaN       22         4        4        0
6      Christopher Street    128,753    4,752     3,358    2,693        0
7               9thStreet    151,566    5,357     4,672    3,758        0
8              14thStreet    246,791    9,111     6,581    5,006        0
9              23rdStreet    221,746    8,932     3,593    2,719        0
10             33rdStreet    952,786   36,569    20,794   16,272        0
11        UPTOWN SUBTOTAL  1,701,642   64,721    38,998   30,448        0
12                    WTC  1,182,685   49,166    14,224   11,036        0
13      NEW YORK SUBTOTAL  2,884,327  113,887    53,222   41,484        0
14    NEW JERSEY STATIONS        NaN      NaN       NaN      NaN      NaN
15                 Newark    707,443   28,682    11,134    7,973        0
16               Harrison    193,913    7,772     3,146    2,586        0
17         Journal Square    702,140   26,839    16,228   11,692        0
18           Grove Street    464,344   17,998    10,218    6,877        0
19         Exchange Place    378,843   15,989     3,973    2,800        0
20       Pavonia/ Newport    492,957   19,169    10,614    7,194        0
21                Hoboken    710,233   28,018    14,172    9,287        0
22    NEW JERSEY SUBTOTAL  3,649,873  144,467    69,485   48,409        0
23          MONTHLY TOTAL  6,534,200  258,354   122,709   89,894        0,                     0          1        2       3       4       5
0  Christopher Street    129,780    4,967   3,132   2,583   1,854
1           9thStreet    146,846    5,277   4,240   3,499   2,606
2          14thStreet    246,408    9,407   6,051   4,808   3,981
3          23rdStreet    213,775    9,066   3,388   2,705   1,993
4          33rdStreet    956,183   37,733  20,207  16,779  16,585
5     UPTOWN SUBTOTAL  1,692,992   66,450  37,018  30,374  27,019
6                 WTC  1,167,092   50,615  15,445  12,854  13,287
7   NEW YORK SUBTOTAL  2,860,084  117,065  52,463  43,228  40,306,                     0       1          2        3        4       5
0  Christopher Street   4,186     99,349   15,661   12,916   1,854
1           9thStreet   4,737    105,545   21,200   17,495   2,606
2          14thStreet   7,949    188,131   30,257   24,039   3,981
3          23rdStreet   6,896    181,319   16,940   13,523   1,993
4          33rdStreet  30,845    754,666  101,036   83,896  16,585
5     UPTOWN SUBTOTAL  54,613  1,329,010  185,094  151,869  27,019
6                 WTC  37,648  1,012,308   77,227   64,270  13,287
7   NEW YORK SUBTOTAL  92,261  2,341,318  262,321  216,139  40,306,                      0        1          2        3        4       5
0               Newark   22,360    584,263   55,272   43,602  10,012
1             Harrison    6,409    160,681   17,754   17,632   2,615
2       Journal Square   22,565    545,256   80,144   61,594  12,524
3         Grove Street   14,909    370,650   48,471   36,637   6,428
4       Exchange Place   11,785    326,122   20,127   15,331   3,753
5     Pavonia/ Newport   15,787    392,847   50,004   38,788   7,763
6              Hoboken   22,066    565,462   63,084   47,353   8,151
7  NEW JERSEY SUBTOTAL  115,881  2,945,281  334,856  260,937  51,246,                         0          1        2         3        4        5
0   PATH Ridership Report        NaN      NaN       NaN      NaN      NaN
1                May 2015        NaN      NaN       NaN      NaN      NaN
2                     NaN   May 2015  Average   Average  Average  Average
3                     NaN     Totals  Weekday  Saturday   Sunday  Holiday
4       NEW YORK STATIONS        NaN       20         5        5        1
5      Christopher Street    129,780    4,967     3,132    2,583    1,854
6               9thStreet    146,846    5,277     4,240    3,499    2,606
7              14thStreet    246,408    9,407     6,051    4,808    3,981
8              23rdStreet    213,775    9,066     3,388    2,705    1,993
9              33rdStreet    956,183   37,733    20,207   16,779   16,585
10        UPTOWN SUBTOTAL  1,692,992   66,450    37,018   30,374   27,019
11                    WTC  1,167,092   50,615    15,445   12,854   13,287
12      NEW YORK SUBTOTAL  2,860,084  117,065    52,463   43,228   40,306
13    NEW JERSEY STATIONS        NaN      NaN       NaN      NaN      NaN
14                 Newark    693,149   29,213    11,054    8,720   10,012
15               Harrison    198,682    8,034     3,551    3,526    2,615
16         Journal Square    699,518   27,263    16,029   12,319   12,524
17           Grove Street    462,186   18,532     9,694    7,327    6,428
18         Exchange Place    365,333   16,306     4,025    3,066    3,753
19       Pavonia/ Newport    489,402   19,642    10,001    7,758    7,763
20                Hoboken    684,050   28,273    12,617    9,471    8,151
21    NEW JERSEY SUBTOTAL  3,592,320  147,263    66,971   52,187   51,246
22          MONTHLY TOTAL  6,452,404  264,330   119,435   95,415   91,552,                     0          1        2       3       4  5
0  Christopher Street    130,852    4,980   3,007   2,314  0
1           9thStreet    138,717    4,889   3,833   3,956  0
2          14thStreet    258,085    9,484   6,442   5,915  0
3          23rdStreet    226,345    9,167   3,196   2,970  0
4          33rdStreet    979,637   37,850  19,639  17,098  0
5     UPTOWN SUBTOTAL  1,733,636   66,370  36,117  32,253  0
6                 WTC  1,251,290   51,846  15,159  12,510  0
7   NEW YORK SUBTOTAL  2,984,926  118,216  51,276  44,763  0,                     0       1          2        3        4  5
0  Christopher Street   4,362    109,570   12,028    9,254  0
1           9thStreet   4,624    107,563   15,332   15,822  0
2          14thStreet   8,603    208,659   25,767   23,659  0
3          23rdStreet   7,545    201,682   12,785   11,878  0
4          33rdStreet  32,655    832,691   78,555   68,391  0
5     UPTOWN SUBTOTAL  57,788  1,460,165  144,467  129,004  0
6                 WTC  41,710  1,140,611   60,637   50,042  0
7   NEW YORK SUBTOTAL  99,498  2,600,776  205,104  179,046  0,                      0        1          2        3        4  5
0               Newark   24,579    656,716   42,583   38,080  0
1             Harrison    6,768    179,744   13,445    9,859  0
2       Journal Square   23,472    590,847   62,381   50,918  0
3         Grove Street   15,925    407,962   39,035   30,749  0
4       Exchange Place   13,219    369,450   15,046   12,082  0
5     Pavonia/ Newport   16,705    431,333   38,800   31,025  0
6              Hoboken   24,208    638,309   49,237   38,702  0
7  NEW JERSEY SUBTOTAL  124,877  3,274,361  260,527  211,415  0,                         0          1        2         3        4        5
0   PATH Ridership Report        NaN      NaN       NaN      NaN      NaN
1               June 2015        NaN      NaN       NaN      NaN      NaN